import 'models/disease.dart';

class DiseasesData{
  static final List<Disease> diseasesList = [
    Disease(
        id: 1,
        imageUrl: "assets/images/Alternaria/AlternariaAva.jpg",
        name: "Alternaria Leaf Blight",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Alternaria/Alternaria1.jpg",
        relatedImage2: "assets/images/Alternaria/Alternaria2.jpg",
        relatedImage3: "assets/images/Alternaria/Alternaria3.jpg",
        relatedImage4: "assets/images/Alternaria/Alternaria4.jpg"),
    Disease(
        id: 2,
        imageUrl: "assets/images/Canker/CankerAva.jpg",
        name: "Canker",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Canker/1.jpg",
        relatedImage2: "assets/images/Canker/2.jpg",
        relatedImage3: "assets/images/Canker/3.jpg",
        relatedImage4: "assets/images/Canker/4.jpg"),
    Disease(
        id: 3,
        imageUrl: "assets/images/Chlorosis/ChlorosisAva.jpg",
        name: "Chlorosis",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Chlorosis/1.jpg",
        relatedImage2: "assets/images/Chlorosis/6.jpg",
        relatedImage3: "assets/images/Chlorosis/130.jpg",
        relatedImage4: "assets/images/Chlorosis/132.jpg"),
    Disease(
        id: 4,
        imageUrl: "assets/images/Esca/EscaAva.jpg",
        name: "Esca",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Esca/872.jpg",
        relatedImage2: "assets/images/Esca/873.jpg",
        relatedImage3: "assets/images/Esca/883.jpg",
        relatedImage4: "assets/images/Esca/904.jpg"),
    Disease(
        id: 5,
        imageUrl: "assets/images/EyeSpot/EyeSpotAva.jpg",
        name: "Eyespot",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/EyeSpot/t1.jpg",
        relatedImage2: "assets/images/EyeSpot/t12.jpg",
        relatedImage3: "assets/images/EyeSpot/t16.jpg",
        relatedImage4: "assets/images/EyeSpot/t22.jpg"),
    Disease(
        id: 6,
        imageUrl: "assets/images/Healthy/HealthyAva.JPG",
        name: "Khoe manh",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Healthy/Healthy1.jpg",
        relatedImage2: "assets/images/Healthy/Healthy2.jpg",
        relatedImage3: "assets/images/Healthy/Healthy3.jpg",
        relatedImage4: "assets/images/Healthy/Healthy4.jpg"),
    Disease(
        id: 7,
        imageUrl: "assets/images/Monilia/MoniliaAva.jpg",
        name: "Monilia",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Monilia/t9.jpg",
        relatedImage2: "assets/images/Monilia/t10.jpg",
        relatedImage3: "assets/images/Monilia/t12.jpg",
        relatedImage4: "assets/images/Monilia/t24.jpg"),
    Disease(
        id: 8,
        imageUrl: "assets/images/NLB/NLBAva.jpg",
        name: "Northern leaf blight",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/NLB/t7.jpg",
        relatedImage2: "assets/images/NLB/t8.jpg",
        relatedImage3: "assets/images/NLB/t18.jpg",
        relatedImage4: "assets/images/NLB/t20.jpg"),
    Disease(
        id: 9,
        imageUrl: "assets/images/PhanTrang/PhanTrangAva.jpg",
        name: "Phan trang",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/PhanTrang/PhanTrang1.jpg",
        relatedImage2: "assets/images/PhanTrang/PhanTrang2.jpg",
        relatedImage3: "assets/images/PhanTrang/PhanTrang3.jpg",
        relatedImage4: "assets/images/PhanTrang/PhanTrang4.jpg"),
    Disease(
        id: 10,
        imageUrl: "assets/images/Rust/RustAva.jpg",
        name: "Rust",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Rust/502.jpg",
        relatedImage2: "assets/images/Rust/503.jpg",
        relatedImage3: "assets/images/Rust/586.jpg",
        relatedImage4: "assets/images/Rust/587.jpg"),
    Disease(
        id: 11,
        imageUrl: "assets/images/SuongMai/SuongMaiAva.jpg",
        name: "Suong mai",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/SuongMai/SuongMai1.jpg",
        relatedImage2: "assets/images/SuongMai/SuongMai2.jpg",
        relatedImage3: "assets/images/SuongMai/SuongMai3.jpg",
        relatedImage4: "assets/images/SuongMai/SuongMai4.jpg"),
    Disease(
        id: 12,
        imageUrl: "assets/images/ThanThu/ThanThuAva.jpg",
        name: "Than thu",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/ThanThu/ThanThu1.jpg",
        relatedImage2: "assets/images/ThanThu/ThanThu2.jpg",
        relatedImage3: "assets/images/ThanThu/ThanThu3.jpg",
        relatedImage4: "assets/images/ThanThu/ThanThu4.jpg"),
    Disease(
        id: 13,
        imageUrl: "assets/images/Cedar-appleRust/Cedar-appleRustAva.jpg",
        name: "Cedar-apple rust",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Cedar-appleRust/t2.jpg",
        relatedImage2: "assets/images/Cedar-appleRust/t12.jpg",
        relatedImage3: "assets/images/Cedar-appleRust/t14.jpg",
        relatedImage4: "assets/images/Cedar-appleRust/t30.jpg"),
    Disease(
        id: 14,
        imageUrl: "assets/images/BlackMold/BlackMoldAva.jpg",
        name: "Black mold",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/BlackMold/30.jpg",
        relatedImage2: "assets/images/BlackMold/53.jpg",
        relatedImage3: "assets/images/BlackMold/54.jpg",
        relatedImage4: "assets/images/BlackMold/55.jpg"),
    Disease(
        id: 15,
        imageUrl: "assets/images/GhostSpot/GhostSpotAva.jpg",
        name: "Ghost spot",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/GhostSpot/1.jpg",
        relatedImage2: "assets/images/GhostSpot/3.jpg",
        relatedImage3: "assets/images/GhostSpot/8.jpg",
        relatedImage4: "assets/images/GhostSpot/31.jpg"),
    Disease(
        id: 16,
        imageUrl: "assets/images/AppleScab/AppleScabAva.jpg",
        name: "Apple scab",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/AppleScab/AppleScab1.jpg",
        relatedImage2: "assets/images/AppleScab/AppleScab2.jpg",
        relatedImage3: "assets/images/AppleScab/AppleScab3.jpg",
        relatedImage4: "assets/images/AppleScab/AppleScab4.jpg"),
    Disease(
        id: 17,
        imageUrl: "assets/images/Verticillium/VerticilliumAva.jpg",
        name: "Verticillium wilt",
        shortDes: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom: "Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
        reason: "Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
        solution: "Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
        relatedImage1: "assets/images/Verticillium/Verticillium1.jpg",
        relatedImage2: "assets/images/Verticillium/Verticillium2.jpg",
        relatedImage3: "assets/images/Verticillium/Verticillium3.jpg",
        relatedImage4: "assets/images/Verticillium/Verticillium4.jpg"),
  ];
}