import 'models/disease.dart';

class DiseasesData{
  static final List<Disease> diseasesList = [
    Disease(
        id: 1,
        imageUrl: "assets/images/Alternaria/AlternariaAva.jpg",
        name:"Alternaria Leaf Blight",
        vname:"Tàn rụi lá do nấm Alternaria",
        shortDes:"Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
        symptom:"- Lá có những đốm nhỏ, tròn, màu nâu vàng nhạt với phần trung tâm màu trắng, sau đó chuyển sang màu nâu nhạt, lan rộng và cho thấy các vòng đồng tâm. \n- Lớp phấn màu xanh ô-liu sẫm ngả đen phủ trên bề mặt trái cây.\n- Các triệu chứng xuất hiện đầu tiên trên các lá già ở phần giữa và phần trên của cây dưới dạng những đốm nhỏ, tròn, màu nâu vàng nhạt với phần trung tâm màu trắng. Những đốm này lan rộng, chuyển sang màu nâu nhạt và tạo thành một vết lõm nhẹ. Các gân lá nhỏ bên trong các đốm này bị sạm lại, dẫn đến có bề ngoài hình lưới. Theo thời gian, các vòng đồng tâm phát triển chỉ có thể nhìn thấy ở mặt trên của lá, cho những đốm này có vẻ ngoài giống như bảng phi tiêu. Những đốm tròn này cuối cùng có thể ảnh hưởng đến toàn bộ lá và lá có thể rụng. Các thương tổn tròn, lõm, màu nâu xuất hiện trên các quả bị nhiễm bệnh, sau đó có thể được bao phủ bởi một lớp phấn màu xanh ô-liu ngả đen. Quả bị nhiễm bệnh nếu không được phát hiện trong khi thu hoạch có thể dẫn đến tổn thất sau này trong quá trình lưu trữ hoặc vận chuyển thu hoạch. Các bộ phận khác của cây không bị ảnh hưởng trực tiếp.",
        more:"- Tên khoa học: Alternaria cucumerina\n- Được tìm thấy trong: Dưa chuột, Cà chua, Cotton, Bí ngô, Bí ngòi, Dưa.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Sử dụng lớp phủ từ rơm ngay sau khi trồng có hiệu quả làm giảm sự lan rộng của bào tử A. cucumerina từ đất lên các lá thấp.",
        chemistry:"- Mancozeb 63.0 WP, Carbendazim 12.0 WP\n- Propiconazole 25.0 EC\n- Difenoconazole 25.0 EC\n- Copper Oxychloride 50.0 WP",
        relatedImage1: "assets/images/Alternaria/Alternaria1.jpg",
        relatedImage2: "assets/images/Alternaria/Alternaria2.jpg",
        relatedImage3: "assets/images/Alternaria/Alternaria3.jpg",
        relatedImage4: "assets/images/Alternaria/Alternaria4.jpg"),
    Disease(
        id: 2,
        imageUrl: "assets/images/Canker/CankerAva.jpg",
        name: "Canker",
        vname:"Bệnh thối đen ở cây",
        shortDes:"Các trường hợp nhiễm bệnh thường bắt đầu từ việc xuất hiện các vết thương tổn dạng lõm màu đỏ ở cành. ",
        symptom:"- Các trường hợp nhiễm bệnh thường bắt đầu từ việc xuất hiện các vết thương tổn dạng lõm màu đỏ ở cành.\n- Về sau, các thương tổn này phát triển thành khu vực thối mục, khiến cành cây bị tróc vỏ rồi chết đi.\n- Ở các cành to, vỏ cây chết đi vẫn lưu lại dấu vết, cho thấy những vòng đồng tâm và các mép nổi gờ.\n- Đôi khi, các quả đang phát triển xuất hiện mắt thối loét khô (thối đuôi quả) quan đài hoa.Có thể quan sát thấy các mảng vỏ chết (thối mục) dạng lõm tròn hay bầu dục trên thân cây và các cành nhánh. Các trường hợp nhiễm bệnh | này thường bắt đầu tại khu vực quanh những vết thương, các chồi búp trên cành hay nhánh non dưới dạng các vết thương tổn lõm hoe đỏ. Về sau, các thương tổn này phát triển thành khu vực thối mục, khiến cành nhánh bị tróc vỏ rồi chết đi chỉ trong một mùa vụ. Ở các cành to, các vết thương tổn xuất hiện dưới dạng các đốm lõm màu nâu đỏ, về sau vỡ ra và để lộ phần gỗ chết ở giữa. Vỏ cây chết đi vẫn lưu lại những vòng đồng tâm tích tụ nhiều năm và các mép nổi gờ điển hình. Các cành nhánh bên trên khu vực thối mục phát triển yếu ớt và chết dần đi. Đôi khi, các quả đang phát triển cũng bị tấn công và xuất hiện vết mắt thối loét khố (thối đuôi quả) quanh đài hoa.",
        more:"- Tên khoa học: Neonectria ditissima\n- Được tìm thấy trong: Táo, Lê.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Cho đến nay, chưa có biện pháp kiểm soát sinh học nào đạt hiệu quả đối kháng loài nấm này. Có thể sử dụng các sản phẩm phủ kín vết thương có gốc kim loại đồng để hạn chế khả năng xảy ra bệnh thối đen cây ở cây ăn quả này.",
        chemistry:" ",
        relatedImage1: "assets/images/Canker/1.jpg",
        relatedImage2: "assets/images/Canker/2.jpg",
        relatedImage3: "assets/images/Canker/3.jpg",
        relatedImage4: "assets/images/Canker/4.jpg"),
    Disease(
        id: 3,
        imageUrl: "assets/images/Chlorosis/ChlorosisAva.jpg",
        name: "Chlorosis",
        vname:"Lá úa vàng do thiếu sắt",
        shortDes:"Lá úa và chuyển sang màu vàng",
        symptom:"- Lá úa và chuyển sang màu vàng.\n- Gân lá vẫn giữ màu xanh.\n- Toàn bộ lá có thể chuyển sang màu vàng trắng với các đốm nâu và các mảng mô chết ở mép lá.\nCác triệu chứng thiếu sắt xuất hiện trước hết ở các lá non, sau đến lá già, vì sắt không di chuyển được từ lá già về lá non. Triệu chứng đặc trưng là | tầng lá trên bị úa màu (chuyển sang màu vàng), trong khi gân giữa và các gân lá còn lại vẫn giữ màu xanh lục rõ ràng qua các mảng giữa gân lá). Ở các giai đoạn sau, nếu không thực hiện biện pháp xử lý nào, toàn bộ lá chuyển sang màu vàng trắng và bắt đầu xuất hiện đốm mê chết màu nâu trên phiến lá, thường dẫn đến tình trạng phát triển các mảng mô chết ở mép lá. Có thể xác định dễ dàng các khu vực bị ảnh hưởng từ một khoảng cách xa. Tình trạng úa vàng và chết mô lá làm giảm hàm lượng chất diệp lục, ức chế tốc độ quang hợp, làm chậm sự tăng trưởng và làm giảm năng suất tiềm năng của cây.",
        more:"Tên khoa học: Iron Deficiency\n- Được tìm thấy trong: Nho, cà chua, táo, dâu tây, dưa chuột, Táo, Lê, Đậu, Ớt, Cà tím, Anh đào, Mơ, Đào, Đậu Hà Lan, Dưa chuột.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Bón phân động vật, than bùn và phân trộn cũng bổ sung sắt cho đất",
        chemistry:"- Sử dụng các loại phân bón có chứa sắt (Fe).\n- Ví dụ: Sắt sunfat (Fe19%).\n- Có thể sử dụng phân bón dạng lỏng có chứa sắt phun trực tiếp lên lá lúa - Tư vấn cán bộ nông nghiệp để biết chủng loại tốt nhất và liều lượng sử dụng phù hợp nhất cho đất và cây trồng.\nCác đề xuất khác:\n- Kiểm nghiệm đất trước khi bắt đầu mùa vụ gieo trồng để phát huy tối đa năng suất cây trồng.",
        relatedImage1: "assets/images/Chlorosis/1.jpg",
        relatedImage2: "assets/images/Chlorosis/6.jpg",
        relatedImage3: "assets/images/Chlorosis/130.jpg",
        relatedImage4: "assets/images/Chlorosis/132.jpg"),
    Disease(
        id: 4,
        imageUrl: "assets/images/Esca/EscaAva.jpg",
        name: "Esca",
        vname:"Bệnh esca",
        shortDes:"Tán lá có sọc vẫn,sau đó lá cây khô,hoại tử và rụng sớm.",
        symptom:"- Tán lá có sọc vẫn,sau đó lá cây khô,hoại tử và rụng sớm.\n- Các đốm tròn nhỏ sậm màu xuất hiện trên quả, hình thành nên những vết nứt.\n- Các vòng đồng tâm xuất hiệnởmặt cắt ngang của thân gỗ.\nBệnh có thể xảy ra vào bất kỳ thời điểm nào trong suốt mùa vụ trồng trọt.Những triệu chứng chính là sọc vằn ởgiữa gân lá,có điểm đặc trưng là các mô bị bạc màu hoặc khô đi quanh gân chính. Thông thường, các sọc này có màu đỏ đậmở các giống nho đỏ hoặc có màu vàng ở các giống nho xanh.Lá có thể bị khô hoàn toàn và rụng sớm. Trên quả,xuất hiện những đốm tròn nhỏ đậm màu,thường được bao quanh bằng một vòng màu nâu tím.Các đốm trên quả có thể xuất hiện ở bất cứ thời điểm nào từ lúc đậu quả đến khi quả chín.Ởnhững cây nho bị nhiễm bệnh nặng,quả thường bị rạn nứt và khô.Cắt ngang các lóng,chồi cành,nhánh chính,hoặc thân nho bị nhiễm bệnh,chúng ta có thể nhận ra những vòng đồng tâm được hình thành bởi những đốm sẫm màu. Một dạng triệu chứng nghiêm trọng của bệnh Esca này được xem như hậu quả của “các mạch bị tắc nghẽn”là tình trạng chết nốn đột ngột trên toàn bộ giàn nho.",
        more:"Tên khoa học: Togninia minima\n- Được tìm thấy ở: Nho",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch.Trong các giai đoạn nặng hơn của bệnh,vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Ngâm các cành giâm vào nước ấm 50°Ctrong khoảng 30 phút.Phương pháp này thường không phải lúc nào cũng hiệu quả,vì vậy nên kết hợp với các phương pháp khác. Một số loài thuộc chi nấm đối kháng Trichoderma đã từng được sử dụng để ngăn ngừa quá trình nhiễm nấm tại các vết cắt tỉa,các đầu gốc của vật liệu nhân giống và các sản phẩm chiết ghép.Biện pháp xử lý này phải được thực hiện trong vòng 24 giờ sau khi cắt tỉa và lập lại sau2tuần.",
        chemistry:"Trong mọi trường hợp,nên xem xét khả năng dung hợp các biện pháp phòng ngừa và các biện pháp kiểm soát sinh học có thể áp dụng được. Các chiến lược sử dụng hóa chất để khống chế bệnh hại này khó đạt được hiệu quả do các loại thuốc diệt nấm mang tính phòng ngừa theo truyền thống thường không thể xâm nhập đủ sâu vào những vết cắt tỉa vào thời kỳ cây nho ngủ đông để gây ảnh hưởng lên nấm.Thực hiện các thông lệ canh tác mang tính phòng ngừa bệnh là cách hiệu quả nhất đối với tất cả các loại bệnh ảnh hưởng đến thân cây.Ví dụ trước khi chiết ghép,sản phẩm chiết ghép cần được nhúng ngập vào trong các loại sáp đặc biệt có chứa các chất điều hòa sinh trưởng hoặc các sản phẩm có công dụng ngăn chặn nấm xâm nhập.Điều đó kích thích sự phát triển các vết chai trên sản phẩm chiết ghép,đồng thời ngăn chặn quá trình nhiễm nấm.",
        relatedImage1: "assets/images/Esca/872.jpg",
        relatedImage2: "assets/images/Esca/873.jpg",
        relatedImage3: "assets/images/Esca/883.jpg",
        relatedImage4: "assets/images/Esca/904.jpg"),
    Disease(
        id: 5,
        imageUrl: "assets/images/EyeSpot/EyeSpotAva.jpg",
        name: "Eyespot",
        vname:"Bệnh mắt đốm",
        shortDes:"Các đốm dạng vết nước loang xuất hiện ở các lá phía dưới.",
        symptom:"Các đốm dạng vết nước loang xuất hiện ở các lá phía dưới.\n- Các tổn thương phát triển thành đốm mắt, với trung tâm màu nâu vàng nhạt và rìa màu nâu sẫm hơn.\n- Các mảng tụ lại và chuyển sang héo.\nCác vết bệnh li ti, dạng vết nước loang, hình tròn xuất hiện ở các lá phía dưới. Các thương tổn lan rộng và phát triển thành đốm mắt, với phần trung tâm màu nâu vàng nhạt, rìa màu nâu sẫm | hơn và có quầng sáng màu vàng lớn hơn. Sauđó, chúng kết hợp lại để tạo thành các mảng mô lúa vàng hoặc hoại tử. Các tổn thương phổ biến nhất trên lá già, nhưng cũng có thể được quan sát trên bẹ lá và vỏ nang (lá bao bắp).",
        more:"- Tên khoa học: Kabatiella zeae\n- Được tìm thấy ở: Ngô",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc",
        organic:"Xin lỗi, chúng tôi không biết bất kỳ phương pháp điều trị thay thế nào chống lại Kabatiella zeae. Hãy liên lạc với chúng tôi trong trường hợp bạn biết cách nào có thể giúp chống lại căn bệnh này. Chúng tôi mong được nghe từ bạn",
        chemistry:"Luôn luôn xem xét phương pháp tích hợp giữa các biện pháp phòng ngừa cùng với phương pháp điều trị sinh học nếu có. Cân nhắc cẩn thận những ưu và nhược điểm của việc xử lý thuốc diệt nấm đối với tiềm năng năng suất, giá trị của cây trồng và chi phí của thuốc diệt nấm. Các phương pháp điều trị nấm bằng thuốc bao gồm: mancozeb, propiconazole và chlorothalonil. Xử lý hạt giống với các hợp chất này cũng có thể được cân nhắc.",
        relatedImage1: "assets/images/EyeSpot/t1.jpg",
        relatedImage2: "assets/images/EyeSpot/t12.jpg",
        relatedImage3: "assets/images/EyeSpot/t16.jpg",
        relatedImage4: "assets/images/EyeSpot/t22.jpg"),
    Disease(
        id: 6,
        imageUrl: "assets/images/Healthy/HealthyAva.JPG",
        name: "Khoe manh",
        vname:"Khoẻ mạnh",
        shortDes:"Cây trồng và thực vật khỏe mạnh có màu xanh đậm tốt và hoa rực rỡ.",
        symptom:"Cây trồng và thực vật khỏe mạnh có màu xanh đậm tốt và hoa rực rỡ.\n- Lá chắc khỏe và cho ra trái giàu dinh dưỡng.\n- Vườn cây tốt khi toàn bộ cây trồng khỏe mạnh.",
        more:"",
        recommend:"Mua cây giống từ các nguồn được chứng nhận. Kiểm tra phần cấy ghép cẩn thận trước khi mua. Trồng cây với khoảng cách vừa đủ để thông gió tốt. Chọn địa điểm (đất,thời tiết)một cách cẩn thận và đảm bảo không gieo các giống dễ nhiễm bệnh. Bón phân với hỗn hợp phân bón phù hợp và cung cấp dinh dưỡng cân bằng.Không tưới quá nhiều nước cho cây trồng trong mùa.Không chạm vào cây khỏe mạnh sau khi tiếp xúc cây nhiễm bệnh.Tránh thay đổi nhiệt độ lớn.Duy trì số lượng lớn các giống cây khác nhau xung quanh vườn cây.Nếu điều trị chống lại dịch bệnh, hãy sử dụng các sản phẩm không ảnh hưởng đến côn trùng có lợi.Loại bỏ lá,quả hoặc cành bị bệnh đúng thời điểm trong mùa sinh trưởng.Vào mùa thu,dọn sạch cành lá khỏi cánh đồng hoặc vườn cây và đốt chúng.",
        organic:"",
        chemistry:"",
        relatedImage1: "assets/images/Healthy/Healthy1.jpg",
        relatedImage2: "assets/images/Healthy/Healthy2.jpg",
        relatedImage3: "assets/images/Healthy/Healthy3.jpg",
        relatedImage4: "assets/images/Healthy/Healthy4.jpg"),
    Disease(
        id: 7,
        imageUrl: "assets/images/Monilia/MoniliaAva.jpg",
        name: "Monilia",
        vname:"Thối quả do nấm monilia",
        shortDes:"Hoa héo úa và chuyển sang màu nâu, các khu vực thối mục phát triển ở các mô gỗ. ",
        symptom:"- Hoa héo úa và chuyển sang màu nâu, các khu vực thối mục phát triển ở các mô gỗ.\n- Các đốm tròn có màu nâu rám nắng xuất hiện trên quả.\n- Bào tử nấm màu xám tro ngả nâu bám thành chùm trên hoa, cành và quả.\n- Quả trên cây trở nên teo tóp và héo khô.\nCác triệu chứng đa dạng tùy theo giống cây trồng nhưng thường được tách ra thành héo úa hoa, thối mục cành và thối nâu quả. Hoa bị nhiễm bệnh sẽ héo úa, chuyển sang màu nâu và thường vẫn bám vào cành. Các mảng thối mục phát triển mô gỗ. Trong điều kiện ẩm ướt, bào tử màu nâu xám tro phát triển thành chùm trên bề mặt của hoa và cành nhiễm bệnh. Một chất nhựa dính thường rỉ ra từ các khu vực thối mục, khiến hoa bị héo úa vẫn dính chặt vào cành. Khả năng quả dễ bị thối nâu tăng trong các giai đoạn quả sắp chín, thường là khoảng 2 - 3 tuần trước khi thu hoạch. Thoạt đầu, có thể nhìn thấy các đốm tròn màu nâu rám nắng trên vỏ quả. Trong điều kiện ẩm ướt, các khối bào tử màu nâu xám tro phát triển bên trong các đốm này. Quả bị bệnh không rơi xuống đất sẽ mất nước dần và héo quắt ngay trên cành.",
        more:"- Tên khoa học: Monilinia fructigena\n- Cũng được tìm thấy trong: Táo, Lê, Anh đào, Mơ, Đào, Hạnh nhân.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Phương pháp bảo quản quả được gọi là làm lạnh bằng nước (hydro-cooling), hay loại bỏ nhiệt từ rau quả mới thu hoạch bằng cách cho chúng tắm trong nước đá, có thể ngăn ngừa sự phát triển của nấm trong giai đoạn lưu trữ hay vận chuyển. Các loại thuốc diệt nấm sinh học có gốc lợi khuẩn Bacillus subtilis có hiệu quả như là tác nhân đối kháng với nấm Monilinia fructigena",
        chemistry:"Nếu có thể hãy luôn xem xét sử dụng phương thức kết hợp các biện pháp phòng ngừa với các biện pháp xử lý sinh học. Việc phun kịp thời và có lặp lại các loại thuốc diệt nấm có gốc dicarboximides, benzimidazoles, triforine, chlorothalonil, myclobutanil, fenbuconazole, propiconazole, fenhexamid và anilinopyrimidines có hiệu quả xử lý loại bệnh hại này. Các loại thuốc diệt nấm mới như pyraclostrobin và boscalid cũng có hiệu quả. Việc phun thuốc hợp lý tùy thuộc vào diễn tiến đồng thời của các bệnh khác như bệnh ghẻ, bệnh đốm trắng, bệnh gỉ sắt, bệnh ghẻ nâu hay bệnh thối mốc xám. Kiểm soát côn trùng cũng là một biện pháp quan trọng để tránh gây các tổn thương cho quả.",
        relatedImage1: "assets/images/Monilia/t9.jpg",
        relatedImage2: "assets/images/Monilia/t10.jpg",
        relatedImage3: "assets/images/Monilia/t12.jpg",
        relatedImage4: "assets/images/Monilia/t24.jpg"),
    Disease(
        id: 8,
        imageUrl: "assets/images/NLB/NLBAva.jpg",
        name: "Northern leaf blight",
        vname:"Bệnh đốm lá lớn",
        shortDes:"Các triệu chứng bệnh xuất hiện đầu tiên trên lá tầng thấp. Các vết tổn thương màu nâu nhạt, dài và hẹp",
        symptom:"- Các triệu chứng bệnh xuất hiện đầu tiên trên lá tầng thấp. Các vết tổn thương màu nâu nhạt, dài và hẹp, có các mép sẫm màu dài 25-150 mm, chạy song song với hai bên mép lá. Bệnh khiến lá khô héo và chết.\nCác triệu chứng ban đầu xuất hiện dưới dạng những đốm nhỏ hình bầu dục, sũng nước, trên các lá ở tầng thấp. Khi bệnh tiến triển, các đốm ấy bắt đầu xuất hiện ở phần bên trên của cây. Các đốm bệnh cũ phát triển dần thành các vết thương hoại tử hình điếu xì gà dài màu nâu vàng với các đốm sẫm màu rõ rệt, có đường viền màu xanh nhạt và sũng nước. Những vết tổn thương ấy sau đó kết tụ lại và bao trùm phần lớn phiến lá và thân cây, đôi khi khiến cây tàn lụi và chết đi. Nếu bệnh lây nhiễm đến các bộ phận bên trên của cây trong quá trình phát triển lõi ngô, tình trạng tổn thất năng suất thu hoạch nghiêm trọng có thể xảy ra (lên đến 70%).",
        more:"- Tên khoa học: Setosphaeria turcica- Được tìm thấy trong: Ngô, Kê, Lúa miến.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Các loại thuốc diệt nấm sinh học có gốc là loài nấm đối kháng Trichoderma harzianum hoặc Bacillus subtilis có thể được sử dụng ở các giai đoạn khác nhau để giảm nguy cơ nhiễm nấm. Sử dụng các loại dung dịch có chứa lưu huỳnh cũng đạt được hiệu quả.",
        chemistry:"Mancozeb 75.0 WP",
        relatedImage1: "assets/images/NLB/t7.jpg",
        relatedImage2: "assets/images/NLB/t8.jpg",
        relatedImage3: "assets/images/NLB/t18.jpg",
        relatedImage4: "assets/images/NLB/t20.jpg"),
    Disease(
        id: 9,
        imageUrl: "assets/images/PhanTrang/PhanTrangAva.jpg",
        name: "Phan trang",
        vname:"Phấn trắng",
        shortDes:"Lớp phấn bao phủ lá có thể được lau sạch.",
        symptom:"- Lớp phấn bao phủ lá có thể được lau sạch.\nBan đầu,những đốm vàng xuất hiệnởmặt trên của lá. Ởgiai đoạn sau của bệnh,lớp phấn màu trắng,sau ngả xám lan rộng phủ lên lá,thân và quả. Nấm hút chất dinh dưỡng từ cây,để lại lớp phủ giống như tro trên lá cản trở quá trình quang hợp làm cây phát triển còi cọc. Khi bệnh tiến triển,các bộ phận bị nhiễm bệnh quăn lại,lá rụng và cây có thể chết. Trái ngược với bệnh sương mai,bệnh phấn trắng có thể được kiểm soát ở một mức độ nào đó.",
        more:"Tên khoa học: Erysiphaceae\nCũng được tìm thấy trong: nho, dâu tây, cà chua, dưa chuột, cotton, lúa mì, táo ",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc",
        organic:"Đối với các khu vườn, dung dịch nước sữa có tác dụng như thuốc diệt nấm tự nhiên. Xịt dung dịch này lên lá cách ngày. Phương thuốc dân gian này hoạt động đặc biệt tốt với cây họ bầu bí (dưa chuột, bí xanh, bí ngô) và quả mọng. Bệnh phấn trắng khác nhau tùy theo cây ký chủ, nên giải pháp này có thể không hiệu quả đối với tất cả các giống cây. Nếu không thấy cải thiện, hãy thử dung dịch natri bicacbonat hoặc tỏi. Phương pháp điều trị sinh học cũng có bán trên thị trường.",
        chemistry:"- Carbendazim 50.0 WP\n- Mancozeb 64.0 WP, Metalaxyl-M 4.0 WP\n- Fluxapyroxad 25.0 SC, Pyraclostrobin 25.0 SC\n- Azoxystrobin 23.0 SV",
        relatedImage1: "assets/images/PhanTrang/PhanTrang1.jpg",
        relatedImage2: "assets/images/PhanTrang/PhanTrang2.jpg",
        relatedImage3: "assets/images/PhanTrang/PhanTrang3.jpg",
        relatedImage4: "assets/images/PhanTrang/PhanTrang4.jpg"),
    Disease(
        id: 10,
        imageUrl: "assets/images/Rust/RustAva.jpg",
        name: "Rust",
        vname:"Gỉ sắt sọc vàng",
        shortDes:"Các nốt mụn nhỏ li ti xếp thành từng sọc. ",
        symptom:"- Các nốt mụn nhỏ li ti xếp thành từng sọc.\n- Thân và ngọn cũng có thể bị ảnh hưởng.\nMức độ nặng nhẹ của bệnh phụ thuộc vào tính mẫn cảm của cây. Ở những giống dễ bị bệnh, nấm tạo ra những nốt mụn nhỏ li ti màu vàng cam (gỉ sắt) xếp thành hàng tạo thành những sọc hẹp song song với gân lá. Cuối cùng chúng hợp nhất và có thể lấn át toàn bộ lá, đặc điểm này xuất hiện sớm hơn ở cây non. Những nốt mụn này (đường kính 0,5 đến 1 mm) đôi khi cũng có thể được tìm thấy trên thân và ngọn. Ở giai đoạn sau của bệnh, trên lá xuất hiện những sọc hoặc đốm dài, hoại tử, màu nâu nhạt, thường bao phủ bởi các nốt mụn rỉ sắt. Trong trường hợp nhiễm bệnh nặng, sự phát triển của cây bị tổn hại nghiêm trọng và các mô bị tổn hại. Diện tích lá giảm dẫn đến năng suất thấp hơn, số cành trên cây ít hơn và số hạt trên cành ít hơn. Nhìn chung, bệnh có thể dẫn đến mất mùa nghiêm trọng.",
        more:"Tên khoa học: Puccinia striiformis\nCũng được tìm thấy trong: Lúa mì, Lúa mạch , Ngô.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Nhiều loại thuốc diệt nấm sinh học có sẵn trên thị trường. Các sản phẩm chứa Bacillus pumilus được phun cách nhau từ 7 đến 14 ngày có hiệu quả chống lại nấm và được tiếp thị bởi người làm trong ngành.",
        chemistry:"Nếu có thể hãy luôn xem xét sử dụng phương thức kết hợp các biện pháp phòng ngừa với các biện pháp xử lý sinh học. Thuốc diệt nấm thuộc nhóm strobilurin phun lên lá giúp bảo vệ hiệu quả chống lại bệnh khi phun phòng ngừa. Ở ruộng đã bị nhiễm bệnh, sử dụng các sản phẩm thuộc họ triazole hoặc hỗn hợp của cả hai sản phẩm.",
        relatedImage1: "assets/images/Rust/502.jpg",
        relatedImage2: "assets/images/Rust/503.jpg",
        relatedImage3: "assets/images/Rust/586.jpg",
        relatedImage4: "assets/images/Rust/587.jpg"),
    Disease(
        id: 11,
        imageUrl: "assets/images/SuongMai/SuongMaiAva.jpg",
        name: "Suong mai",
        vname:"Sương mai",
        shortDes:"Các đốm lá màu vàng xuất hiện ở mặt trên lá",
        symptom:"- Các đốm lá màu vàng xuất hiện ở mặt trên lá.\n- Dạng cấu trúc mịn như nhung,màu xám nhạt, phát triển ở mặt dưới lá.\n- Các chồi non,hoa và quả phát triển thấp bé và yếu ớt.\n- Cây phát triển còi cọc.\nMặc dù có sự khác biệt nhỏ tùy theo từng loài cây trồng,bệnh sương mai trên các cây thuộc họ bầu bí thường có đặc trưng là sự phát triển của các đốm lá màu vàng, có góc cạnh, ở mặt trên của lá và không lan rộng ra ngoài các gân chính. Tình trạng úa vàng giữa các gân lá này dần dần hình thành một dạng khảm màu vàng ngả nâu không nên bị nhầm lẫn với bệnh nhiễm vi-rút.Ở mặt dưới lá,các tổn thương bủng nước xuất hiện ngay bên dưới những đốm vàng nêu trên, dần dần chuyển sang dạng mịn màn như nhung, có màu xám nhạt,trong điều kiện nhiệt độ mát mẻ, độ ẩm cao và kéo dài.Vì loài nấm gây bệnh này hút chất dinh dưỡng từ cây nên có thể khiến cây bị thấp lùn,chồi non,hoa hoặc quả thui chột và chết dần,dẫn đến tình trạng cây phát triển còi cọc và cho năng suất kém.Không giống như triệu chứng của bệnh phấn trắng,lớp phủ nấm mốc chỉ xuất hiện ở mặt dưới của lá và sự phát triển của nó bị hạn chế bởi các gân chính.Hơn nữa,lớp phủ ấy không thể được loại bỏ một cách dễ dàng.",
        more:"Tên khoa học:Pseudoperonospora cubensis\nCũng được tìm thấy trong: Bí ngô, Bí ngòi, Dưa chuột, Mướp đẳng",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch.Trong các giai đoạn nặng hơn của bệnh,vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Trên thị trường đã có bán các sản phẩm xử lý sinh học để đối phó với loài nấm hại này. Trong trường hợp nhiễm nhẹ,tốt hơn là không nên làm gì và đợi cho đến khi thời tiết trở nên tốt hơn. Trong một số trường hợp,các loại thuốc diệt nấm hữu cơ có tác dụng phòng ngừa trước khi nhiễm bệnh có thể giúp cây tránh bị nhiễm nấm, bao gồm các loại thuốc diệt nấm có gốc kim loại đồng,chẳng hạn như hỗn hợp Bordeaux.",
        chemistry:"Dimethomorph 20.27 SC, Smetoctradin 27.0 SC \n Pyraclostrobin 5.0 WG, Metiram 55.0 WG \n Azoxystrobin 23.0 SC",
        relatedImage1: "assets/images/SuongMai/SuongMai1.jpg",
        relatedImage2: "assets/images/SuongMai/SuongMai2.jpg",
        relatedImage3: "assets/images/SuongMai/SuongMai3.jpg",
        relatedImage4: "assets/images/SuongMai/SuongMai4.jpg"),
    Disease(
        id: 12,
        imageUrl: "assets/images/ThanThu/ThanThuAva.jpg",
        name: "Than thu",
        vname:"Thán thư",
        shortDes:"Ban đầu, lá có những vết bệnh màu nâu tạo thành những vòng tròn đồng tâm.",
        symptom:"- Ban đầu, lá có những vết bệnh màu nâu tạo thành những vòng tròn đồng tâm. Khi nấm bệnh gây hại nặng hơn sẽ thấy các ổ nấm màu đen nằm trên vòng tròn rất rõ.\n- Trên thân, vết bệnh bị lõm vào và có màu vàng, sau đó chuyển sang màu đen, trên mặt vết lõm có lớp phấn dày màu hồng. Nếu trời khô chỗ vết bệnh tạo thành các đường nứt, trời ẩm thì chỗ đó sẽ bị thối.\n- Trên trái, vết bệnh có màu nâu đen, tròn, đường kính 2-4mm",
        more:"- Tên khoa học: Colletotrichum lagenarium\n- Được tìm thấy trong: Dưa chuột, Cây cà chua, cây mè(vừng), ớt, các cây họ bầu bí, dưa, cây ăn trái,...",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Các chế phẩm hữu cơ chứa kim loại đồng đã được phê chuẩn để sử dụng đối phó với bện thán thư ở họ bầu bí mang lại kế quả khá tốt. Các chế phẩm kiểm soát sinh học Bacillus subtilis cũng có bán trên thị trường",
        chemistry:"Hexaconazole 5.0 EC\nChlorothalonil 75.0 WP\nCarbendazim 50.0 WP\nMancozeb 75.0 WP",
        relatedImage1: "assets/images/ThanThu/ThanThu1.jpg",
        relatedImage2: "assets/images/ThanThu/ThanThu2.jpg",
        relatedImage3: "assets/images/ThanThu/ThanThu3.jpg",
        relatedImage4: "assets/images/ThanThu/ThanThu4.jpg"),
    Disease(
        id: 13,
        imageUrl: "assets/images/Cedar-appleRust/Cedar-appleRustAva.jpg",
        name: "Cedar-apple rust",
        vname:"Bệnh nấm Cedar",
        shortDes:"- Các đốm tròn màu đỏ cam sáng xuất hiện trên mặt trên của lá.",
        symptom:"- Các đốm tròn màu đỏ cam sáng xuất hiện trên mặt trên của lá.\n- Các mầm màu nâu và giống như mụn cây phát triển ở mặt dưới của lá.\n- Đôi khi, có những vết thối mục lõm trong vỏ cành và thân non.\nCác đốm tròn nhỏ, màu nâu, phát triển đầu tiên ở mặt trên của lá. Khi chúng to lên, chúng chuyển sang màu đỏ cam tươi với tâm màu nâu sẫm. Vào cuối mùa hè, có thể quan sát thấy các mầm giống như mụn, màu nâu, giống như hạt ở mặt dưới của lá. Đôi khi, nấm cũng có thể gây ra các thương tổn và thối mục lõm trên vỏ cành và thân non. Mặc dù quả không bị ảnh hưởng trực tiếp nhưng nếu bị nhiễm trùng nặng có thể làm rụng lá và mất mùa.",
        more:"- Tên khoa học: Gymnosporangium sabinae\n- Được tìm thấy trong: Táo,Lê",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Cho đến nay, chưa có phương pháp điều trị sinh học nào được biết đến cho bệnh này.",
        chemistry:"Nếu có thể hãy luôn xem xét sử dụng phương thức kết hợp các biện pháp phòng ngừa với các biện pháp xử lý sinh học. Mức độ nhiễm trùng thấp thường không phải là vấn đề và có thể bỏ qua. Thuốc diệt nấm chứa difenoconazole có thể được sử dụng để kiểm soát bệnh. Đối với những người làm vườn tại nhà, thuốc diệt nấm tebuconazole, tebuconazole với trifloxystrobin và triticonazole được chấp thuận để kiểm soát bệnh gỉ sắt.",
        relatedImage1: "assets/images/Cedar-appleRust/t2.jpg",
        relatedImage2: "assets/images/Cedar-appleRust/t12.jpg",
        relatedImage3: "assets/images/Cedar-appleRust/t14.jpg",
        relatedImage4: "assets/images/Cedar-appleRust/t30.jpg"),
    Disease(
        id: 14,
        imageUrl: "assets/images/BlackMold/BlackMoldAva.jpg",
        name: "Black mold",
        vname:"Mốc đen",
        shortDes:"- Các đốm tròn nhỏ màu nâu đỏ xuất hiện trên lá và quả, có quầng màu vàng xanh bao quanh",
        symptom:"- Các đốm tròn nhỏ màu nâu đỏ xuất hiện trên lá và quả, có quầng màu vàng xanh bao quanh.\n- Các đốm lan rộng dần.\n- Quả bị thối rữa.\nLoài nấm gây bệnh này gây ra hai nhóm triệu chứng chính ở cây lựu cũng như cây cà chua, nhưng không nhất thiết xuất hiện xảy ra cùng một lúc. Thường ấy được gọi chung là đốm đen và thối ruột quả, các triệu chứng ấy xuất hiện phụ thuộc vào giống cây trồng. Bệnh đốm đen có đặc trưng là sự xuất hiện của các đốm tròn nhỏ màu nâu đỏ hay đen (kích cỡ khoảng 1-3 mm), bao quanh bởi một quầng vàng ngả xanh, trên quả và lá cây. Khi bệnh tiến triển, các đốm ấy hợp lại với nhau và hình thành nên các mảng lớn hơn, có thể chiếm đến 50% bề mặt quả. Trên lá, các đốm ấy lúa vàng và có thể khiến lá rụng sớm. Phần bên ngoài của quả bắt đầu thối rữa trong khi các mô ăn được bên trong không bị tổn hại. Màu vỏ hay hình dáng quả thay đổi hơi bất thường có thể là các dấu hiệu bên ngoài của tình trạng thối rỗng bên trong, nhưng thường thì quả vẫn giữ được vẻ bề ngoài lành mạnh cho đến khi thu hoạch. Đến khi quả được cắt ra, các phần áo hạt thối rữa mới lộ rõ.",
        more:"- Tên khoa học: Black Mold\n- Được tìm thấy trong: Cà chua, Táo, Lê, Đậu, Ớt, Đu đủ, Dưa, Lựu.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Chưa có biện pháp xử lý sinh học nào để đối phó với loài nấm Alternaria alternata. Tuy nhiên, các sản phẩm có gốc đồng oxychloride đã được chứng minh là có hiệu quả cao trong việc khống chế bệnh này ở cây lựu cũng như ở cây cà chua.",
        chemistry:"Hãy luôn xem xét đến khả năng kết hợp giữa các biện pháp phòng ngừa và các biện pháp xử lý sinh học, trong phạm vi có thể áp dụng được. Phun thuốc phòng bệnh hai lần trong giai đoạn cây trổ hoa hoặc khi các triệu chứng đầu tiên xuất hiện trên quả có thể giúp khống chế bệnh một cách hiệu quả. Các sản phẩm thuốc có gốc propiconazole, thiophanate methyl hay azoxystrobine đã được chứng minh là đạt hiệu quả cao. Điều quan trọng là nên tuân thủ các quy định về hàm lượng thuốc và nên sử dụng các loại thuốc diệt nấm với các phương thức khác nhau để tránh tình trạng nấm đề kháng thuốc.",
        relatedImage1: "assets/images/BlackMold/30.jpg",
        relatedImage2: "assets/images/BlackMold/53.jpg",
        relatedImage3: "assets/images/BlackMold/54.jpg",
        relatedImage4: "assets/images/BlackMold/55.jpg"),
    Disease(
        id: 15,
        imageUrl: "assets/images/GhostSpot/GhostSpotAva.jpg",
        name: "Ghost spot",
        vname:"Bệnh mốc xám",
        shortDes:"Bệnh mốc xám có thể được quan sát thấy trên lá, chồi, quả hoặc vỏ quả.",
        symptom:"- Bệnh mốc xám có thể được quan sát thấy trên lá, chồi, quả hoặc vỏ quả.\n- Các mảng nấm có lông màu xám ngả nâu phát triển trên các mô.\n- Các bộ phận của cây bị ảnh hưởng héo, chuyển sang màu nâu và thối nhũn.\n- Đôi khi, có thể thấy cành bị chết khô và hình thành vết loét trên các cây thân gỗ.\nSự phát triển mạnh mẽ của nấm mốc trên lá, chồi, vỏ hoặc quả là triệu chứng nổi bật nhất. Ban đầu, các vết thương thưa thớt, sạm hoặc nâu và ngậm nước xuất hiện trên các bộ phận của cây tiếp xúc với đất hoặc đã bị tổn thương. Các mảng nấm có lông và màu xám ngả nâu phát triển trên các mô này. Sau đó, nấm mốc phát triển trên quả non và vỏ, cho chúng vẻ ngoài lông lá. Ngoài ra, các triệu chứng xuất hiện trong quá trình lưu trữ. Trong cả hai trường hợp, có thể có tổn thất nghiêm trọng. Thối lá ở gần gốc và thân cây gây ra mất mùa toàn diện trong trường hợp giống cây trồng dễ bị tổn thương (chết vì úng nước). Đôi khi, có thể thấy cành bị chết khô và hình thành vết loét trên các cây thân gỗ.",
        more:"- Tên khoa học: Botrytis cinerea\n- Cũng được tìm thấy trong: Táo, Nho, Đậu, Ớt, Cà tím, Anh đào, Đậu Hà Lan, Dưa chuột, Bí ngô, Bí ngòi, Cải bắp, Khoai tây, Đậu triều & Đậu đỏ, Đậu gà & Đậu xanh, Hạnh nhân, Dâu tây, Lý chua, Chỉ cam chanh, Lạc/Đậu phộng, Xoài, Lựu, Cải dầu, Đậu lăng.",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Thuốc diệt nấm sinh học có chứa nấm cạnh tranh Trichoderma harzianum có hiệu quả chống nấm mốc xám trên nhiều loại cây trồng. Các sản phẩm có chứa Streptomyces griseovirides cũng được sử dụng trên rau diếp.",
        chemistry:"Captan 75.0 WP",
        relatedImage1: "assets/images/GhostSpot/1.jpg",
        relatedImage2: "assets/images/GhostSpot/3.jpg",
        relatedImage3: "assets/images/GhostSpot/8.jpg",
        relatedImage4: "assets/images/GhostSpot/31.jpg"),
    Disease(
        id: 16,
        imageUrl: "assets/images/AppleScab/AppleScabAva.jpg",
        name:"Apple scab",
        vname:"Nấm táo",
        shortDes:"- Những đốm nhỏ màu xanh xám hoặc nâu xuất hiện trên lá. ",
        symptom:"- Những đốm nhỏ màu xanh xám hoặc nâu xuất hiện trên lá.\n- Về sau hình thành nên những mảng lớn màu nâu.\n- Lá biến dạng và rụng sớm.\n- Trên quả, xuất hiện những mảng sần, cứng màu nâu sẫm.\n- Quả méo mó và nứt nẻ.\nCác triệu chứng dễ nhận thấy đầu tiên của bệnh ghẻ ở táo xuất hiện vào mùa xuân dưới dạng các đốm tròn nhỏ màu xanh xám trên lá, thường phân bố dọc theo gân chính của lá. Khi các đốm này lan rộng, chúng chuyển sang màu nâu đen và cuối cùng hợp lại với nhau thành các mảng mô chết khá lớn. Các lá bị nhiễm bệnh thường biến dạng và rụng sớm, dẫn đến tình trạng cây trơ lá khi bị nhiễm nặng. Ở chồi, những phần bị nhiễm bệnh phồng giộp và nứt ra, tạo điều kiện cho các mầm bệnh cơ hội xâm nhập vào cây. Ở quả, những mảng tròn nâu ngả nâu đen xuất hiện trên bề mặt. Chúng phát triển lớn dần rồi hợp lại với nhau, nổi sần và thô cứng, hạn chế quá trình phình căng của quả và dẫn đến tình trạng quả bị méo mó, vỏ quả nứt nẻ lộ cả phần thịt quả bên trong. Các tác động của ánh sáng không gây ảnh hưởng đáng kể đối với chất lượng quả. Mặt khác, các đốm ghẻ này có thể tạo điều kiện cho các mầm bệnh cơ hội và tình trạng thối rữa xâm nhập sâu vào thịt quả, làm giảm chất lượng quả và khả năng lưu giữ quả trong thời gian dài.",
        more:"- Tên khoa học: Venturia inequalis\n- Được tìm thấy trong: Táo",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch. Trong các giai đoạn nặng hơn của bệnh, vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Nếu bệnh này đã từng phát triển mạnh trong vườn trồng ở mùa trước, có thể phun các dung dịch thuốc diệt nấm có kim loại đồng để cản trở quá trình phát triển của nấm trên cây vào mùa đông. Phun lưu huỳnh chỉ có hiệu quả phần nào đối với bệnh ghẻ ở táo này. Tuy vậy, các dung dịch có chứa lưu huỳnh và pyrethrins là giải pháp hữu cơ khả dụng để kiểm soát loại bệnh này trong mùa sinh trưởng của cây.",
        chemistry:"-Hexaconazole 5.0 EC\n- Carbendazim 50.0 WP\n- Captan50.0 WP\n- Myclobutanil 10.0 WP",
        relatedImage1: "assets/images/AppleScab/AppleScab1.jpg",
        relatedImage2: "assets/images/AppleScab/AppleScab2.jpg",
        relatedImage3: "assets/images/AppleScab/AppleScab3.jpg",
        relatedImage4: "assets/images/AppleScab/AppleScab4.jpg"),
    Disease(
        id: 17,
        imageUrl: "assets/images/Verticillium/VerticilliumAva.jpg",
        name: "Verticillium wilt",
        vname:"Bệnh héo rũu do nấm verticillium wilt",
        shortDes:"Lá úa vàng-bắt đầu từ mép lá.",
        symptom:"- Lá úa vàng-bắt đầu từ mép lá.\n- Gân lá chính vẫn xanh.\n- Thân cây có các sọc màu đen.\n- Cây héo rũ.\nCác triệu chứng rất đa dạng tùy theo các loại cây trồng khác nhau.Thông thường, triệu chứng úa vàng thành mảng giữa các gân lá xuất hiện đầu tiên ở mép các lá già. Khi tình trạng úa vàng phát triển đến phần còn lại của mô lá,lá có vẻ héo rũ, thường là chỉ ở một mặt.Triệu chứng đặc trưng ấy được gọi là úa vàng khu vực hay héo rũ một mặt. Triệu chứng này thể hiện rõ lúc tiết trời nắng ấm.Trên thân cây,các dải màu đen phát triển và lan dần từ gốc cây trở lên,dẫn đến tình trạng héo rũ thân.Các triệu chứng chủ yếu là cây phát triển kém,lá già sớm,toàn bộ các nhánh cây còi cọc và chết.Các triệu chứng bổ sung có thể xuất hiện là mô gỗốdần dưới dạng các vòng hay vệt tròn.Đôi khi,quan sát gần với một chiếc kính lúp,chúng ta có thể thấy các đốm đen nhỏ ở phần mô đang chết dần cũng như trên các mô còn sống.",
        more:"-Tên khoa học: Verticillium spp.\n-Được tìm thấy trong: dưa chuột, nho, cotton, dâu tây, cà chua, Nho, Đậu, Ớt, Cà tím,",
        recommend:"Chúng tôi khuyên bạn nên áp dụng biện pháp kiểm soát hữu cơ trong giai đoạn đầu của bệnh hoặc khi cây trồng gần thu hoạch.Trong các giai đoạn nặng hơn của bệnh,vui lòng sử dụng biện pháp kiểm soát bằng hóa chất. Không nên trộn hoặc sử dụng các sản phẩm khác nhau cùng một lúc.",
        organic:"Các loại thuốc diệt nấm bằng chất sinh học có chứa vi khuẩn Streptomyces lydicus có khả năng phá vỡ vòng đời của nấm và hỗ trợ khống chế quá trình phát triển của dịch bệnh này.",
        chemistry:"Nếu có thể, hãy luôn cân nhắc giải pháp dung hợp giữa các biện pháp phòng ngừa và các biện pháp xử lý sinh học.Khi cây bị nhiễm bệnh,rất khó để trừ bệnh.Sử dụng các loại thuốc xông đất là một biện pháp khống chế bệnh hiệu quả nhưng khá tốn kém. Hiệu quả chống bệnh tùy thuộc vào chủng loại và tỷ lệ hóa chất sử dụng, cũng như tùy thuộc vào các điều kiện môi trường tại thời điểm sử dụng. Xử lý các bộ phận của cây bị nhiễm bệnh cũng cần được tiên liệu và hoạch định từ trước",
        relatedImage1: "assets/images/Verticillium/Verticillium1.jpg",
        relatedImage2: "assets/images/Verticillium/Verticillium2.jpg",
        relatedImage3: "assets/images/Verticillium/Verticillium3.jpg",
        relatedImage4: "assets/images/Verticillium/Verticillium4.jpg"),
  ];
}