const RE_DATA  = [
  {
    "image":"assets/images/AlternariaAva.jpg",
    "name":"Alternaria Leaf Blight",
    "shortDes":"Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện ...",
    "symptom":"Alternaria lead blight đầu tiên lây nhiễm lá trưởng thành gần vương miện của cây. Các đốm lá bắt đầu như những đốm nâu nhỏ, thường có quầng vàng và phát triển thành các đốm nâu không đều (lên đến 3/4). Các đốm lá đôi khi phát triển một mô hình giống như mục tiêu của vòng. Lá bị nhiễm bệnh nặng chuyển sang màu nâu, cuộn tròn lên trên, héo và chết. Trái cây có thể bị phơi nắng do rụng lá. Họ không phải là nạn nhân phổ biến.",
    "reason":"Dòng gió có thể mang Alternaria cucumerina một khoảng cách dài. Alternaria cucumerina cũng có thể lan rộng trong lĩnh vực này bằng cách bắn nước. Thời tiết ẩm ướt, mưa ủng hộ bệnh tật. Thiệt hại có thể rất nghiêm trọng trong điều kiện ấm áp, ẩm ướt. Nấm sống sót từ mùa này sang mùa khác trong các mảnh vụn thực vật.",
    "solution":"Xoay rau để một địa điểm đi ba năm trở lên mà không trồng bất kỳ thành viên nào của gia đình bí đao. Sử dụng tưới nhỏ giọt thay vì vòi phun nước trên cao nếu có thể. Không làm việc trong thực vật khi ướt. Loại bỏ và tiêu diệt cây bị nhiễm bệnh vào cuối mùa trong những khu vườn nhỏ. Trên những cánh đồng lớn, cho đến khi còn dư lượng cây trồng vào cuối mùa. Một số thuốc diệt nấm có sẵn để sử dụng chống lại bệnh tàn phá lá Alternaria. Thuốc xịt phòng ngừa có hiệu quả nhưng chỉ cần thiết trong các lĩnh vực có tiền sử bệnh tàn phá lá Alternaria.",
    "relatedImage1":"assets/images/Alternaria1.jpg",
    "relatedImage2":"assets/images/Alternaria2.jpg",
    "relatedImage3":"assets/images/Alternaria3.jpg",
    "relatedImage4":"assets/images/Alternaria4.jpg"
  },
  {
    "image":"assets/images/PhanTrangAva.jpg",
    "name":"Phấn Trắng",
    "shortDes":"Bệnh phấn trắng gây hại phổ biến trên hầu hết các cây trồng thuộc họ bầu...",
    "symptom":"Bệnh nấm phấn trắng trên dưa lưới gây hại tất cả các bộ phận của cây. Bệnh phát sinh phát triển và phá hại ngay từ thời kỳ cây con. Khi mới phát sinh, vết bệnh trên lá ban đầu là những mảng nhỏ mất màu xanh chuyển sang màu vàng, có bao phủ một lớp phấn màu trắng dày như bột phấn, bao chùm lên toàn bộ phiến lá. Khi nhiễm bệnh lá chuyển sang màu vàng, lá khô và dễ rụng. Bệnh nặng lớp phấn trắng lan xuống cả thân, cành và hoa làm cho hoa bị khô chết. Cây bị nhiễm bệnh phát triển kém, năng suất giảm nghiêm trọng.",
    "reason":"Bệnh phấn trắng do nấm Erysiphe cichoarcearum gây ra. Đây là loài nấm túi, ký sinh chuyên tính. Sợi nấm bám dày đặc trên bề mặt lá tạo các vòi hút chọc sâu vào trong tế bào cây ký chủ hút các chất dinh dưỡng. Cành bào tử nấm phân sinh thẳng góc với sợi nấm, không phân nhánh, không màu. Bào tử phân sinh hình trứng hoặc bầu dục, đơn bào, không màu, kích thước 5-7micromet.",
    "solution":"Dinh dưỡng cân đối đầy đủ, không để cây thừa thiếu dinh dưỡng, bổ sung dinh dưỡng theo nhu cầu của cây (từng giai đoạn).\nPhun phòng định kỳ chế phẩm nano bạc đồng plus, nano đồng oxyclorua: Dùng 50ml chế phẩm nano bạc đồng plus kết hợp với 50ml nano đồng oxyclorua pha với 20 lít nước phun đều lên tán lá, định kỳ 10-15 ngày/lần",
    "relatedImage1":"assets/images/PhanTrang1.jpg",
    "relatedImage2":"assets/images/PhanTrang2.jpg",
    "relatedImage3":"assets/images/PhanTrang3.jpg",
    "relatedImage4":"assets/images/PhanTrang4.jpg"
  },
  {
    "image":"assets/images/SuongMaiAva.jpg",
    "name":"Sương Mai",
    "shortDes":"Bệnh gây hại phổ biến trên lá, xuất hiện từ lúc cây được 3 lá thật đến c...",
    "symptom":"Bệnh gây hại phổ biến trên lá, xuất hiện từ lúc cây được 3 lá thật đến cuối vụ. Bệnh thường bắt đầu từ tầng lá phía dưới rồi lan dần lên trên. Bệnh xuất phát từ mặt dưới lá. Vết bệnh rải rác khắp mặt lá. Đặc trưng vết bệnh có hình đa giác góc cạnh rất rõ. Sáng sớm quan sát kỹ mặt dưới lá có lớp bụi màu hơi tím, sũng ướt và dễ mất đi dưới ánh sáng mặt trời. Đây cũng là đặc điểm dùng để nhận biết bệnh trực tiếp từ đồng ruộng. Lớp bụi này chính là cơ quan sinh sản của nấm và phát tán nhờ gió. Khi già, vết bệnh đổi màu cam đến nâu đỏ rồi đến nâu sậm, xung quanh vết bệnh có viền vàng. Lá bệnh khô, rách và co rúm lại sau đó khô vàng, rụng đi, trên cây chỉ còn lại những lá non, cây phát triển kém, trái nhỏ. Bệnh có thể lây lan sang cả thân, cành, hoa và trái. Bị nặng cây có thể chết",
    "reason":"Bệnh do nấm Pseudoperonospora cubensis gây ra, phát triển nhanh trong điều kiện ẩm độ không khí cao, trời râm mát, đặc biệt là buổi sáng có sương mù lúc đó bệnh có thể tấn công cả lá non ở tầng trên. Nếu thời tiết khô hanh, bệnh lây lan chậm và chỉ xuất hiện ở tán lá dưới. Bệnh xuất hiện quanh năm trên ruộng dưa, nhưng nặng nhất là trong mùa mưa, trong một vụ, bệnh thường hại nặng giai đoạn sau.",
    "solution":"-Chọn giống kháng bệnh.\n - Không trồng liên tục nhiều vụ dưa trong năm để hạn chế sự tích tụ nguồn bệnh cho vụ sau.\n- Sau khi thu hoạch, dọn sạch tàn dư cây trồng.\n- Tỉa bỏ những cành nhỏ vô hiệu giúp ruộng dưa thông thoáng, làm sạch cỏ gốc để hạn chế sự lây lan.\n- Ngắt bỏ bớt các lá già và lá bệnh, dùng màng phủ nông nghiệp, không để lá tiếp xúc với mặt đất.\n- Sử dụng các loại thuốc hóa học như: Ridomil Gold 68WP, Daconil 500 SC, Curzate M8 72 WP, Nativo 750WG,… hoặc có thể ngừa bằng những loại thuốc gốc đồng như: Funguran-OH 50WP, Champion 77WP, Kocide 61,4 DF,… phun khi cây dưa có 3-4 lá thật.\nChú ý: Nên phun ướt đều 2 mặt lá chủ yếu là mặt dưới lá, phun 2-3 lần, mỗi lần cách nhau 7-10 ngày. Nếu sử dụng thuốc gốc đồng phải phun đúng nồng độ thuốc được khuyến cáo, không phun quá liều vì lá dưa rất mẫn cảm với đồng. Tuân thủ đúng thời gian cách ly được ghi trên nhãn thuốc.",
    "relatedImage1":"assets/images/SuongMai1.jpg",
    "relatedImage2":"assets/images/SuongMai2.jpg",
    "relatedImage3":"assets/images/SuongMai3.jpg",
    "relatedImage4":"assets/images/SuongMai4.jpg"
  },
  {
    "image":"assets/images/ThanThuAva.jpg",
    "name":"Thán Thư",
    "shortDes":"Triệu chứng thán thư xảy ra trên tất cả các phần trên mặt đất của câ...",
    "symptom":"Triệu chứng thán thư xảy ra trên tất cả các phần trên mặt đất của cây dưa leo và bệnh xuất hiện suốt trong thời gian sinh trưởng của cây, nhưng đặc biệt gây hại mạnh ở giai đoạn hình thành trái.\n- Trên lá: ở giai đoạn cây con, hai lá mầm sẽ bị tấn công gây chết cây con. Ở cây lớn hơn, bệnh xuất hiện ở các lá già bên dưới trước, vết bệnh lúc đầu hình tròn nhỏ, màu xanh xám, ướt đẫm nước nổi lên gần những đường gân và to ra nhanh chóng, sau lớn lên, xung quanh có màu nâu vàng, ở giữa vết bệnh màu nâu đậm hơn và có các đường vòng đồng tâm .\n- Bệnh phát triển nặng các vết bệnh lớn lên, khô lan dần ra, kết hợp lại dẫn đến cháy lá, và cuối cùng các lá bị khô từng phần, các trung tâm của vết bệnh bị khô, chết nứt và rách, tạo ra một vẻ ngoài rách rưới cho tán lá và cuối cùng là khô chết cả lá .\n- Trên cuống, thân: các vết bệnh trên cuống lá, cuống trái và thân cây có hình thon dài và hơi chìm, lúc đầu có những đốm nhỏ màu nâu sậm, sau đó, đốm rộng hơn và có màu xám, dẫn đến sự rụng lá, rụng trái và sau đó thân khô,cây chết. Trái non có thể chuyển sang màu đen và chết nếu cuống của chúng bị nhiễm bệnh.\n- Trên trái: trái cây có thể bị nhiễm bệnh khi bắt đầu trưởng thành, vết bệnh hình tròn, màu nâu vàng, lõm vào vỏ trái, giữa vết bệnh nứt ra và mầm bệnh tạo ra bào tử trên trái bị nhiễm bệnh nên xuất hiện lớp mốc hồng, ướt nơi vết bệnh. Bệnh nặng, các vết bệnh liên kết thành mảng lớn gây thối trái, nhũn nước.Trái bị nhiễm bệnh có thể có vị đắng, bị ảnh hưởng nhanh chóng khi bị xâm nhập gây hại bởi các sinh vật  thứ cấp khác gây thối, mềm.\n- Triệu chứng trên trái có thể chưa biểu hiện ngoài đồng mà tiếp tục phát triển sau khi thu hoạch, dẫn đến nhiễm bệnh trái dưa leo trong khi sơ chế, bảo quản hay tiêu thụ ảnh hưởng đến chất lượng trái thương phẩm",
    "reason":"Bệnh do nấm Colletotrichum orbiculare (hay còn gọi là Colletotrichum lagenarium)gây bệnh thán thư. Đĩa đài có những lông cứng màu nâu. Trong đĩa đài có các đính bào tử. Đính bào tử chỉ gồm một tế bào hình trụ thon dài không màu và có kích thước khoảng 4 - 6 x 13 - 19 micromet (Hình 1). Mầm bệnh có thể lưu tồn trong đất, xác bả thực vật hay bám trên bề mặt hạt giống, trái. Bệnh thường xảy ra vào những tháng có mưa nhiều, bào tử nấm lây lan chủ yếu do mưa. Ký chủ: Tác nhân gây bệnh này có thể tấn công tất cả các cây họ bầu bí dưa, nhưng nghiêm trọng nhất là dưa leo và dưa hấu.",
    "solution":"- Sử dụng các giống có tính kháng hoặc chống chịu với bệnh thán thư có thể làm giảm đáng kể tổn thất năng suất. Không để hạt giống từ những trái bị bệnh, xử lý hạt giống trước khi gieo bằng các loại thuốc trừ nấm.\n- Có thể sử dụng cây giống ghép để trồng: kỹ thuật cấy ghép với hạt giống sạch bệnh và kiểm tra cấy ghép trong nhà kính thường xuyên.\n- Ruộng bị bệnh nặng cần luân canh với cây trồng khác (ngoài họ bầu, bí, dưa) ít nhất 1 năm.\n- Lên luống cao, thoát nước tốt không để ứ đọng nước lâu khi tưới tiêu đặc biệt là trong mùa mưa.\n- Thu thập và đốt hoặc cày sâu tất cả các tàn dư cây trồng bị nhiễm bệnh sau khi thu hoạch, sau đó bón vôi để khử trùng, hạn chế sự lây lan cho vụ sau.\n- Quản lý tốt cỏ dại, hạn chế tối đa sự có mặt của cỏ dại trong ruộng trồng dưa leo.\n- Trước khi trồng cần tăng cường bón phân hữu cơ hoai mục và chế phẩm nấm Tricoderma Bacillus HLC có tác dụng hạn chế sự phát triển của mầm bệnh.\n- Bón phân cân đối, tăng cường bón lân và kali, tránh bón thừa phân đạm.\n- Bổ sung Sillic cho vườn dưa leo bằng chế phẩm Nano Silic cũng có tác dụng phòng ngừa bệnh tốt, tăng khả năng dẫn truyền dinh dưỡng và tăng khả năng kháng bệnh trên cây trồng.\n- Tránh làm tổn thương trái khi thu hoạch. \n- Sử dụng phòng trừ bằng bộ đặc trị nấm khuẩn Nano bạc đồng và Nano đồng oxyclorua HLC. Bộ sản phẩm có hiệu quả trong việc kiểm soát bệnh thán thư trên cây dưa leo và các đối tượng cây trồng. Để có hiệu quả phòng trị cao của thuốc diệt nấm bà con cần áp dụng phòng trừ thường xuyên hơn trong mùa mưa để duy trì hiệu quả (khoảng 10-14 ngày/lần), phun khi cây mới chớm bệnh.",
    "relatedImage1":"assets/images/ThanThu1.jpg",
    "relatedImage2":"assets/images/ThanThu2.jpg",
    "relatedImage3":"assets/images/ThanThu3.jpg",
    "relatedImage4":"assets/images/ThanThu4.jpg"
  },
  {
    "image":"assets/images/VerticilliumAva.jpg",
    "name":"Verticillium Wilt",
    "shortDes":"Các triệu chứng rất đa dạng tùy theo các loại cây trồng khác nhau. Thôn...",
    "symptom":"Các triệu chứng rất đa dạng tùy theo các loại cây trồng khác nhau. Thông thường, triệu chứng úa vàng thành mảng giữa các gân lá xuất hiện đầu tiên ở mép các lá già. Khi tình trạng úa vàng phát triển đến phần còn lại của mô lá, lá có vẻ héo rũ, thường là chỉ ở một mặt. Triệu chứng đặc trưng ấy được gọi là úa vàng khu vực hay héo rũ một mặt. Triệu chứng này thể hiện rõ lúc tiết trời nắng ấm. Trên thân cây, các dải màu đen phát triển và lan dần từ gốc cây trở lên, dẫn đến tình trạng héo rũ thân. Các triệu chứng chủ yếu là cây phát triển kém, lá già sớm, toàn bộ các nhánh cây còi cọc và chết. Các triệu chứng bổ sung có thể xuất hiện là mô gỗ ố dần dưới dạng các vòng hay vệt tròn. Đôi khi, quan sát gần với một chiếc kính lúp, chúng ta có thể thấy các đốm đen nhỏ ở phần mô đang chết dần cũng như trên các mô còn sống. ",
    "reason":" Các triệu chứng nêu trên do một nhóm nấm mốc sinh ra từ đất gây ra, trong số đó phải kể đến V. dahliae, loài nấm có thể sống trên các tàn dư cây trồng còn nằm trong đất trong thời gian không có cây ký chủ. Loài nấm này xâm nhập mô mạch của cây thông qua các rễ con hay các vết thương ở vỏ cây. Một khi đã xâm nhập vào cơ thể cây, nấm phát triển nhanh chóng và chặn đứng quá trình vận chuyển nước và chất dinh dưỡng trong cây, gây nên tình trạng héo úa và thối rữa các bộ phận của cây tiếp xúc với không khí (lá và thân). Ở các giai đoạn cuối của bệnh, nấm chiếm giữ các mô chết và hình thành các cấu trúc sẫm màu có thể quan sát được qua kính phóng đại. Nấm có thể tồn tại nhiều năm ở một địa điểm nhất định. ",
    "solution":"Kiểm soát sinh học:\n - Các loại thuốc diệt nấm bằng chất sinh học có chứa vi khuẩn Streptomyces lydicus có khả năng phá vỡ vòng đời của nấm và hỗ trợ khống chế quá trình phát triển của dịch bệnh này. \nKiểm soát hóa học:\n-  Nếu có thể, hãy luôn cân nhắc giải pháp dung hợp giữa các biện pháp phòng ngừa và các biện pháp xử lý sinh học. Khi cây bị nhiễm bệnh, rất khó để trừ bệnh. Sử dụng các loại thuốc xông đất là một biện pháp khống chế bệnh hiệu quả nhưng khá tốn kém. Hiệu quả chống bệnh tùy thuộc vào chủng loại và tỷ lệ hóa chất sử dụng, cũng như tùy thuộc vào các điều kiện môi trường tại thời điểm sử dụng. Xử lý các bộ phận của cây bị nhiễm bệnh cũng cần được tiên liệu và hoạch định từ trước. \nBiện pháp phòng ngừa:\n-  Sử dụng các giống cây trồng có khả năng kháng và chịu bệnh cao là biện pháp tốt nhất. \n-  Không xen canh với các cây mẫn cảm với bệnh vì chúng có thể khiến bệnh phát tán thêm. \n-  Tránh sử dụng các loại phân bón giàu đạm và tưới quá nhiều nước. \n-  Sử dụng các loại thuốc dưỡng cây để tăng cường sức đề kháng của cây đối với dịch bệnh. \n-  Xén tỉa, loại bỏ và đốt sạch các cây và bộ phận của cây đã nhiễm bệnh. \n-  Vệ sinh sạch sẽ mọi công cụ và thiết bị làm đồng sau khi xử lý các cây bị nhiễm bệnh. \n-  Không nên làm việc ngoài đồng khi tán lá còn ướt. \n-  Cẩn thận để không gây tổn hại rễ cây khi làm việc trên đồng. \n-  Phơi đất dưới ánh sáng mặt trời một thời gian (phơi sáng mặt trời). \n-  Loại bỏ và chôn sâu tàn dư cây lá dưới đất hoặc đốt sạch chúng. \n-  Luân canh với các cây không phải là ký chủ của bệnh này. ",
    "relatedImage1":"assets/images/Verticillium1.jpg",
    "relatedImage2":"assets/images/Verticillium2.jpg",
    "relatedImage3":"assets/images/Verticillium3.jpg",
    "relatedImage4":"assets/images/Verticillium4.jpg"
  }
];